CREATE TABLE IF NOT EXISTS `rankdb` (
    `gameid` BIGINT NOT NULL,
    `gamerank` INT NOT NULL,
    `startDtm` DATETIME DEFAULT NULL,
    `Weapon_1` INT DEFAULT NULL,
    `Weapon_2` INT DEFAULT NULL,
    `Weapon_3` INT DEFAULT NULL,
    `characterNum_1` INT DEFAULT NULL,
    `characterNum_2` INT DEFAULT NULL,
    `characterNum_3` INT DEFAULT NULL,
    `damage_1` INT DEFAULT NULL,
    `damage_2` INT DEFAULT NULL,
    `damage_3` INT DEFAULT NULL,
    `damageFromPlayer_1` INT DEFAULT NULL,
    `damageFromPlayer_2` INT DEFAULT NULL,
    `damageFromPlayer_3` INT DEFAULT NULL,
    `nickname_1` VARCHAR(100) DEFAULT NULL,
    `nickname_2` VARCHAR(100) DEFAULT NULL,
    `nickname_3` VARCHAR(100) DEFAULT NULL,
    `playerkill_1` INT DEFAULT NULL,
    `playerkill_2` INT DEFAULT NULL,
    `playerkill_3` INT DEFAULT NULL,
    `matchingmode` INT DEFAULT NULL,
    `avg_ranktier` DOUBLE DEFAULT NULL,
    `avg_getmmr` DOUBLE DEFAULT NULL,
    `avg_rankpoint` DOUBLE DEFAULT NULL,
    PRIMARY KEY (`gameid`, `gamerank`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE IF NOT EXISTS `normaldb` (
    `gameid` BIGINT NOT NULL,
    `gamerank` INT NOT NULL,
    `startDtm` DATETIME DEFAULT NULL,
    `Weapon_1` INT DEFAULT NULL,
    `Weapon_2` INT DEFAULT NULL,
    `Weapon_3` INT DEFAULT NULL,
    `characterNum_1` INT DEFAULT NULL,
    `characterNum_2` INT DEFAULT NULL,
    `characterNum_3` INT DEFAULT NULL,
    `damage_1` INT DEFAULT NULL,
    `damage_2` INT DEFAULT NULL,
    `damage_3` INT DEFAULT NULL,
    `damageFromPlayer_1` INT DEFAULT NULL,
    `damageFromPlayer_2` INT DEFAULT NULL,
    `damageFromPlayer_3` INT DEFAULT NULL,
    `nickname_1` VARCHAR(100) DEFAULT NULL,
    `nickname_2` VARCHAR(100) DEFAULT NULL,
    `nickname_3` VARCHAR(100) DEFAULT NULL,
    `playerkill_1` INT DEFAULT NULL,
    `playerkill_2` INT DEFAULT NULL,
    `playerkill_3` INT DEFAULT NULL,
    `matchingmode` INT DEFAULT NULL,
    `avg_ranktier` DOUBLE DEFAULT NULL,
    `avg_getmmr` DOUBLE DEFAULT NULL,
    `avg_rankpoint` DOUBLE DEFAULT NULL,
    PRIMARY KEY (`gameid`, `gamerank`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
