export type Character = {
  id: number
  name: string
  image: string
}

const characterImageMap: Record<string, string> = {
  Adela: "/character_img/Adela_Mini_00.png",
  Adina: "/character_img/Adina_Mini_00.png",
  Adriana: "/character_img/Adriana_Mini_00.png",
  Aiden: "/character_img/Aiden_Mini_00.png",
  Alex: "/character_img/Alex_Mini_00.png",
  Alonso: "/character_img/Alonso_Mini_00.png",
  Arda: "/character_img/Arda_Mini_00.png",
  Bernice: "/character_img/bERnice_Mini_00.png",
  Bianca: "/character_img/Bianca_Mini_00.png",
  Cathy: "/character_img/Cathy_Mini_00.png",
  Charlotte: "/character_img/Charlotte_Mini_00.png",
  Chiara: "/character_img/Chiara_Mini_00.png",
  Chloe: "/character_img/Chloe_Mini_00.png",
  Daniel: "/character_img/Daniel_Mini_00.png",
  Darko: "/character_img/Darko_Mini_00.png",
  DebiMarlene: "/character_img/DebiMarlene_Mini_00.png",
  Echion: "/character_img/Echion_Mini_00.png",
  Elena: "/character_img/Elena_Mini_00.png",
  Estelle: "/character_img/Estelle_Mini_00.png",
  Eva: "/character_img/Eva_Mini_00.png",
  Fiora: "/character_img/Fiora_Mini_00.png",
  Garnet: "/character_img/Garnet_Mini_00.png",
  Hart: "/character_img/Hart_Mini_00.png",
  Hyejin: "/character_img/Hyejin_Mini_00.png",
  Hyunwoo: "/character_img/Hyunwoo_Mini_00.png",
  Isaac: "/character_img/Isaac_Mini_00.png",
  Jan: "/character_img/Jan_Mini_00.png",
  Jenny: "/character_img/Jenny_Mini_00.png",
  Johann: "/character_img/Johann_Mini_00.png",
  Karla: "/character_img/Karla_Mini_00.png",
  Katja: "/character_img/Katja_Mini_00.png",
  Kenneth: "/character_img/Kenneth_Mini_00.png",
  Leni: "/character_img/Leni_Mini_00.png",
  Lenore: "/character_img/Lenore_Mini_00.png",
  Lenox: "/character_img/Lenox_Mini_00.png",
  Leon: "/character_img/Leon_Mini_00.png",
  Luke: "/character_img/Luke_Mini_00.png",
  "Ly anh": "/character_img/Ly anh_Mini_00.png",
  Mai: "/character_img/Mai_Mini_00.png",
  Markus: "/character_img/Markus_Mini_00.png",
  Martina: "/character_img/Martina_Mini_00.png",
  Mirka: "/character_img/Mirka_Mini_00.png",
  Nadine: "/character_img/Nadine_Mini_00.png",
  Nathapon: "/character_img/Nathapon_Mini_00.png",
  Nicky: "/character_img/Nicky_Mini_00.png",
  Piolo: "/character_img/Piolo_Mini_00.png",
  Priya: "/character_img/Priya_Mini_00.png",
  Rio: "/character_img/Rio_Mini_00.png",
  Shoichi: "/character_img/Shoichi_Mini_00.png",
  Silvia: "/character_img/Silvia_Mini_00.png",
  Sissela: "/character_img/Sissela_Mini_00.png",
  Sua: "/character_img/Sua_Mini_00.png",
  Theodore: "/character_img/Theodore_Mini_00.png",
  Tia: "/character_img/Tia_Mini_00.png",
  Tsubame: "/character_img/Tsubame_Mini_00.png",
  Vanya: "/character_img/Vanya_Mini_00.png",
  Xiukai: "/character_img/Xiukai_Mini_00.png",
  Yuki: "/character_img/Yuki_Mini_00.png",
  Zahir: "/character_img/Zahir_Mini_00.png",
}

export const getCharacterImage = (name: string) => {
  const normalizedName = name.split(" - ")[0]
  return characterImageMap[normalizedName] ?? "/placeholder.svg"
}

export const characters: Character[] = [
  { id: 1, name: "Garnet", image: getCharacterImage("Garnet") },
  { id: 2, name: "Nadine", image: getCharacterImage("Nadine") },
  { id: 3, name: "Nathapon", image: getCharacterImage("Nathapon") },
  { id: 4, name: "Daniel", image: getCharacterImage("Daniel") },
  { id: 5, name: "Darko", image: getCharacterImage("Darko") },
  { id: 6, name: "DebiMarlene", image: getCharacterImage("DebiMarlene") },
  { id: 7, name: "Tia", image: getCharacterImage("Tia") },
  { id: 8, name: "Lenox", image: getCharacterImage("Lenox") },
  { id: 9, name: "Leni", image: getCharacterImage("Leni") },
  { id: 10, name: "Leon", image: getCharacterImage("Leon") },
  { id: 11, name: "Luke", image: getCharacterImage("Luke") },
  { id: 12, name: "Lenore", image: getCharacterImage("Lenore") },
  { id: 13, name: "Rio", image: getCharacterImage("Rio") },
  { id: 14, name: "Martina", image: getCharacterImage("Martina") },
  { id: 15, name: "Mai", image: getCharacterImage("Mai") },
  { id: 16, name: "Markus", image: getCharacterImage("Markus") },
  { id: 17, name: "Mirka", image: getCharacterImage("Mirka") },
  { id: 18, name: "Chloe", image: getCharacterImage("Chloe") },
  { id: 19, name: "Johann", image: getCharacterImage("Johann") },
  { id: 20, name: "Tsubame", image: getCharacterImage("Tsubame") },
  { id: 21, name: "Hyunwoo", image: getCharacterImage("Hyunwoo") },
  { id: 22, name: "Shoichi", image: getCharacterImage("Shoichi") },
  { id: 23, name: "Yuki", image: getCharacterImage("Yuki") },
  { id: 24, name: "Zahir", image: getCharacterImage("Zahir") },
]
